-- Update schema.sql

CREATE TABLE IF NOT EXISTS journal_prompts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    prompt TEXT NOT NULL,
    rating TEXT DEFAULT NULL CHECK (rating IN ('pos', 'neg'))
);

-- Sample Data
INSERT INTO journal_prompts (prompt, rating) VALUES 
('What is one thing you are grateful for today, and why?', 'pos'),
('Describe a challenge you faced recently. How did you handle it, and what did you learn?', 'pos'),
('Write about a moment that made you smile today. What was special about it?', 'pos'),
('What is something new you want to learn, and why does it interest you?', 'pos'),
('Reflect on a past mistake. What would you do differently if faced with a similar situation?', 'pos'),
('How do you define success in your personal or professional life? Has your definition changed over time?', 'pos'),
('Write about a person who inspires you. What qualities do they possess that you admire?', 'pos'),
('What are three things you want to accomplish this week? How will you achieve them?', 'pos'),
('Describe a place where you feel at peace. Why is it special to you?', 'pos'),
('What are some habits or routines that help you stay productive? How did you develop them?', 'pos'),
('Write about a book, movie, or song that has had a significant impact on you. What did you take away from it?', 'pos'),
('How do you handle stress or overwhelming situations? What strategies work best for you?', 'pos'),
('Describe a time when you stepped out of your comfort zone. What was the outcome?', 'pos'),
('What are three qualities you value most in relationships (friendship, romantic, or professional)?', 'pos'),
('If you could give your younger self one piece of advice, what would it be?', 'pos'),
('What does self-care look like for you, and how do you practice it?', 'pos'),
('Write about a goal you''re working towards. What progress have you made, and what are your next steps?', 'pos'),
('Think about a recent conversation that left a strong impression on you. What made it memorable?', 'pos'),
('What is something you are looking forward to, and why?', 'pos'),
('Reflect on how you''ve changed in the past year. What personal growth have you experienced?', 'pos');

-- witchy-nature-spiritual
INSERT INTO journal_prompts (prompt, rating) VALUES 
('What is your connection to the moon? How do its phases influence you?', 'pos'),
('Write about a time you felt deeply connected to nature. What was the experience like?', 'pos'),
('What animal do you feel most drawn to spiritually, and why?', 'pos'),
('If you could cast a spell for personal growth, what would it be and how would you use it?', 'pos'),
('Describe a time you felt the presence of a spirit or guide. What message did you receive?', 'pos'),
('How do you incorporate elements of nature (earth, air, fire, water) into your daily life?', 'pos'),
('What crystal or stone resonates with you most? How does its energy make you feel?', 'pos'),
('Write about a dream you had that felt spiritually significant. What do you think it means?', 'pos'),
('What intention would you like to set during the next new moon?', 'pos'),
('What is your favorite time of day for spiritual practice or connection with nature?', 'pos'),
('Write a letter to your future self from a place of spiritual wisdom.', 'pos'),
('What plants or herbs do you feel drawn to? How do you use them in your spiritual or daily life?', 'pos'),
('What is the most powerful ritual you''ve ever performed? How did it make you feel?', 'pos'),
('How does your spirituality connect you to your intuition? What guidance has it given you recently?', 'pos'),
('What is your favorite season, and how do you connect with it on a spiritual level?', 'pos'),
('Describe a moment when you felt truly aligned with the universe. What was the catalyst?', 'pos'),
('What kind of divination practice (tarot, runes, pendulum, etc.) do you feel most drawn to?', 'pos'),
('Write about a time you experienced a synchronicity or meaningful coincidence. What did it teach you?', 'pos'),
('How does the energy of the earth help ground you during difficult times?', 'pos'),
('What does "witchcraft" mean to you, and how do you practice it in your own life?', 'pos'),
('What messages do you receive when you meditate in nature? What are they trying to teach you?', 'pos'),
('Describe your spiritual relationship with the elements—how does fire, water, earth, and air speak to you?', 'pos'),
('What does your altar look like, and what items or symbols hold significant spiritual meaning for you?', 'pos'),
('How do you connect to your ancestors or the spirits of the past?', 'pos'),
('What would a perfect ritual for self-care look like for you?', 'pos'),
('If you could spend a day with any spirit, deity, or mythical figure, who would it be and why?', 'pos'),
('Write about a time you worked with the energy of a full moon. What intentions or magic did you focus on?', 'pos'),
('What role does intuition play in your spiritual practices?', 'pos'),
('Write about the power of your breath. How does conscious breathing help you connect to spirit?', 'pos'),
('What does your spirit animal teach you, and how do you honor it?', 'pos'),
('Describe a moment when you felt the energy of a forest, ocean, or mountain. How did it affect your mood?', 'pos'),
('How do you feel when you work with candles or flame in your practice?', 'pos'),
('Write about a time you felt deeply connected to a tree. What did the tree communicate to you?', 'pos'),
('What kind of ritual do you feel drawn to perform during a seasonal change?', 'pos'),
('Describe your relationship with the stars or constellations. What do they symbolize for you?', 'pos'),
('What would your ideal magical garden look like, and what plants would you grow there?', 'pos'),
('How does music or sound play a role in your spiritual practices?', 'pos'),
('If you could perform a healing spell for someone, what would it entail and how would you visualize the outcome?', 'pos'),
('What is the most profound spiritual experience you''ve had in nature? How did it change you?', 'pos'),
('How do you prepare your space before performing a ritual or spell?', 'pos'),
('What message do you think your ancestors would want you to know or remember?', 'pos'),
('Write about a time you felt the presence of a deity or divine energy. What was the experience like?', 'pos'),
('How do you celebrate the changing of the seasons or the wheel of the year?', 'pos'),
('If you could live in any mythical realm or magical place, where would it be and why?', 'pos'),
('What role does protection magic play in your spiritual practices? How do you feel protected?', 'pos'),
('Write about an experience when you felt empowered by the energy of the earth beneath you.', 'pos'),
('What is your relationship with the spirit world? How do you communicate with spirits or guides?', 'pos'),
('How do you honor the sacredness of your body in your spiritual practice?', 'pos'),
('Describe a ritual that feels particularly powerful for you during the solstices or equinoxes.', 'pos'),
('What does the concept of balance mean to you in your spiritual life, and how do you maintain it?', 'pos'),
('What plant or tree has the most spiritual significance to you? Why do you feel connected to it?', 'pos'),
('How do you use the elements of nature (water, fire, earth, air) for cleansing or energy clearing?', 'pos'),
('Write about a dream or vision you''ve had involving a witch or a spiritual figure. What message did they bring?', 'pos'),
('What is the most powerful symbol in your spiritual practice, and what does it represent?', 'pos'),
('How do you invoke protection or shielding in your daily life or magical work?', 'pos'),
('What practices help you connect with your higher self or spirit guides?', 'pos'),
('How do you honor the ancestors of the land you live on?', 'pos'),
('What is your relationship with the sun? How do its cycles influence you spiritually?', 'pos'),
('Write about a time you felt a strong connection to the earth. What was happening around you?', 'pos'),
('How do you use intention-setting to manifest your desires or goals?', 'pos'),
('What does "magic" mean to you, and how do you incorporate it into your life?', 'pos');


-- mental health 
INSERT INTO journal_prompts (prompt, rating) VALUES 
('What are the small steps you can take today to feel better about yourself?', 'pos'),
('Describe a time when you felt overwhelmed. What helped you get through it?', 'pos'),
('What self-care practices help you feel grounded when anxiety starts to rise?', 'pos'),
('What does ''burnout'' feel like to you, and what have you learned about your own limits?', 'pos'),
('When you are feeling down, what are three things you can do to lift your mood?', 'pos'),
('Write about a time when you felt disconnected from others. What would have helped you feel more supported?', 'pos'),
('What are the common triggers that lead to feelings of depression or anxiety? How can you manage them?', 'pos'),
('How do you take care of your mental health when things feel too heavy to carry?', 'pos'),
('What are some activities or hobbies that help you feel calm and relaxed during stressful times?', 'pos'),
('How can you show yourself more compassion when you''re struggling with negative thoughts?', 'pos'),
('What are three things you''re proud of accomplishing recently, no matter how small?', 'pos'),
('Describe a time when you felt hopeful during a difficult period. What helped you find hope?', 'pos'),
('How do you set healthy boundaries with others to protect your mental health?', 'pos'),
('What is one positive affirmation you can repeat to yourself when you feel overwhelmed by negative thoughts?', 'pos'),
('Write about a person in your life who supports your mental health. What do they do to help you?', 'pos'),
('When you feel socially anxious, what are three grounding techniques that help calm your nerves?', 'pos'),
('How do you stay present in the moment when your mind starts to spiral with worries or fears?', 'pos'),
('What are some ways you can incorporate mindfulness or meditation into your daily routine to reduce stress?', 'pos'),
('What would your ideal mental health toolkit look like? What strategies or practices would it include?', 'pos'),
('How do you celebrate progress in your mental health journey, even if it''s small or gradual?', 'pos'),
('Write about a time when you asked for help with your mental health. How did that experience make you feel?', 'pos'),
('What negative self-talk do you often struggle with, and how can you counter it with a more compassionate response?', 'pos'),
('What are three self-care rituals you can incorporate into your week to prevent burnout?', 'pos'),
('How do you manage your energy when you feel emotionally drained or burnt out?', 'pos'),
('What are the first signs that you''re starting to feel burnt out, and how can you address them early?', 'pos'),
('How can you better prioritize rest and relaxation in your daily life to protect your mental health?', 'pos'),
('What is your relationship with social media, and how does it affect your mental health?', 'pos'),
('What would it look like to set healthy emotional boundaries with others?', 'pos'),
('Write about a time when you felt misunderstood. How can you communicate your needs more clearly next time?', 'pos'),
('When you''re experiencing a low mood, what activities or people help you feel more connected?', 'pos'),
('How can you reframe a negative thought into a more constructive or compassionate one?', 'pos'),
('What is one thing you can do today to make your environment more calming and supportive for your mental health?', 'pos'),
('Write about a time when you overcame a challenge related to social anxiety. What worked for you?', 'pos'),
('What is your relationship with perfectionism, and how does it impact your mental health?', 'pos'),
('How do you cope with feelings of loneliness or isolation? What support systems can you lean on?', 'pos'),
('When you''re feeling overwhelmed, what are the first steps you can take to regain a sense of control?', 'pos'),
('What strategies have helped you manage feelings of helplessness or hopelessness during tough times?', 'pos'),
('What does ''self-compassion'' mean to you, and how can you practice it more often?', 'pos'),
('How do you create a supportive mental health routine, even when life feels chaotic or stressful?', 'pos'),
('What are the early signs of burnout, and how can you recognize them before it becomes overwhelming?', 'pos'),
('Write about a time when you had to take a break from a social situation. How did you recharge afterwards?', 'pos'),
('What is your relationship with rest, and how can you give yourself permission to rest without guilt?', 'pos'),
('How do you manage the pressure of expectations, both from yourself and others, without sacrificing your well-being?', 'pos'),
('What are some activities you can do to help reset your mind when you''re feeling mentally exhausted?', 'pos'),
('How can you make peace with your imperfections and let go of unrealistic standards?', 'pos'),
('Write about a time when you felt proud of yourself for setting healthy boundaries. What did you learn?', 'pos'),
('What are some ways you can cultivate gratitude, even when you''re feeling down or stressed?', 'pos'),
('How can you support your mental health by changing your environment or routine when you''re feeling stuck?', 'pos'),
('What role does physical activity play in supporting your mental well-being, and what types of movement help you the most?', 'pos'),
('What does a healthy relationship with your emotions look like, and how can you nurture it?', 'pos'),
('How can you practice being gentle with yourself during moments of self-doubt or insecurity?', 'pos'),
('What support systems do you have in place for when you''re feeling mentally overwhelmed or exhausted?', 'pos'),
('Write about a moment when you felt at peace with yourself. What circumstances allowed for that peace?', 'pos'),
('What are some practical ways you can bring more joy or creativity into your daily life, especially during tough times?', 'pos'),
('How do you acknowledge and process your feelings of anxiety or sadness without judgment?', 'pos'),
('What is one thing you can do for yourself today that would help alleviate feelings of depression or anxiety?', 'pos'),
('Write about a positive coping strategy you''ve learned for dealing with stress or overwhelming emotions.', 'pos');

-- self improvement
INSERT INTO journal_prompts (prompt, rating) VALUES 
('What does being a good person mean to you, and how do you live in alignment with those values?', 'pos'),
('Write about a time when you made a mistake. What did you learn from it, and how did it help you grow?', 'pos'),
('What are three qualities you admire in others? How can you develop those qualities in yourself?', 'pos'),
('How do you define success in your life, and what steps can you take to achieve it?', 'pos'),
('What are your core values, and how can you align your daily actions with them?', 'pos'),
('What are the most important habits you can cultivate to become a better person?', 'pos'),
('Write about a time when you helped someone without expecting anything in return. How did it make you feel?', 'pos'),
('What does kindness mean to you, and how can you practice more kindness in your everyday life?', 'pos'),
('In what ways can you become a better listener, both to others and to yourself?', 'pos'),
('How do you handle conflicts, and what strategies can you use to resolve them in a healthy, respectful way?', 'pos'),
('What is one thing you can do today to make someone else''s day a little brighter?', 'pos'),
('Write about a time when you forgave someone, including yourself. What was the impact of that forgiveness?', 'pos'),
('How do you show appreciation for the people in your life? How can you express it more often?', 'pos'),
('What is something you would like to improve about your communication skills, and how can you work on it?', 'pos'),
('How do you show empathy toward others, especially when you don''t understand their situation?', 'pos'),
('What is one small act of self-care that can improve your life right now?', 'pos'),
('How can you challenge negative self-talk and replace it with positive affirmations?', 'pos'),
('What is one personal goal you want to achieve this year, and what steps will you take to reach it?', 'pos'),
('How do you practice gratitude, and how does it change your perspective on life?', 'pos'),
('What strengths do you possess that you are proud of, and how can you use them to help others?', 'pos'),
('Write about a time when you made a positive impact in someone else''s life. How can you create more opportunities like this?', 'pos'),
('What are the habits that contribute to your well-being, and how can you make them a part of your daily routine?', 'pos'),
('What is one way you can show up for yourself with more compassion?', 'pos'),
('How do you balance being kind to others with taking care of your own needs?', 'pos'),
('Write about a challenge you are facing right now. What strengths can you tap into to overcome it?', 'pos'),
('What is the most important lesson you''ve learned about personal growth, and how has it shaped you?', 'pos'),
('What are three things you can do today to be a better version of yourself?', 'pos'),
('How can you be more present in your interactions with others?', 'pos'),
('What does it mean to live with integrity, and how do you practice it in your daily life?', 'pos'),
('What personal habits do you want to break, and how can you replace them with more positive behaviors?', 'pos'),
('What is your relationship with failure, and how can you use it as an opportunity for growth?', 'pos'),
('Write about a time when you acted with courage. How did it feel, and what did you learn from the experience?', 'pos'),
('What are your top priorities right now, and how do they align with your values and long-term goals?', 'pos'),
('How do you deal with self-doubt, and what practices can you use to build your confidence?', 'pos'),
('What does it mean to be authentic, and how can you express your true self more openly?', 'pos'),
('How can you be more patient with yourself and others in challenging situations?', 'pos'),
('Write about a time when you stepped outside your comfort zone. What did you learn from the experience?', 'pos'),
('What are three ways you can contribute to your community or the world around you?', 'pos'),
('What does being a good role model look like to you, and how can you embody that in your life?', 'pos'),
('What is one way you can show more generosity to others, without expecting anything in return?', 'pos'),
('How do you manage your emotions in difficult situations, and how can you improve in this area?', 'pos'),
('What is your relationship with self-discipline, and how can you cultivate more of it in your life?', 'pos'),
('What does self-respect mean to you, and how do you demonstrate it in your actions?', 'pos'),
('How do you practice humility in your life, and what has it taught you about personal growth?', 'pos'),
('Write about a habit you''ve recently developed that has improved your life. How can you make it stick?', 'pos'),
('What role does mindfulness play in your personal growth, and how can you incorporate it into your daily routine?', 'pos'),
('How can you practice self-compassion when you fall short of your expectations?', 'pos'),
('What would your ideal version of yourself look like, and what are the first steps you can take to become that person?', 'pos'),
('What is one area of your life where you would like to experience more growth? How can you start working on it?', 'pos'),
('What does it mean to have a growth mindset, and how can you embrace it in your life?', 'pos'),
('How do you balance ambition with contentment in your life?', 'pos'),
('What is one personal boundary you need to set in order to improve your well-being?', 'pos'),
('How can you contribute to your own happiness, and what steps can you take to cultivate more joy?', 'pos'),
('Write about a time when you made a conscious decision to improve your character. What did that look like?', 'pos'),
('What are three things you can do to be more intentional with your time and energy?', 'pos'),
('How do you deal with negative influences in your life, and what changes can you make to surround yourself with positivity?', 'pos'),
('What would it look like if you fully embraced your potential? What steps can you take to reach it?', 'pos'),
('How can you take responsibility for your own happiness and personal growth?', 'pos');

-- random
INSERT INTO journal_prompts (prompt, rating) VALUES
('Describe the most uncomfortable encounter you''ve had with a stranger. What made it so cringey?', 'pos'),
('What is the weirdest thing you''ve overheard in a public place that you couldn''t unhear?', 'pos'),
('Write about a time you accidentally sent a text to the wrong person. What was your immediate reaction?', 'pos'),
('What''s the oddest thing you''ve ever found in your pocket after washing your clothes?', 'pos'),
('Describe a situation where you accidentally stepped into someone else''s personal space bubble. How did it feel?', 'pos'),
('What''s the most awkward silence you''ve experienced in a conversation? What made it feel so strange?', 'pos'),
('What''s the most bizarre dream you''ve had recently, and how did it make you feel upon waking up?', 'pos'),
('Write about a time when you discovered something hidden in your home that you had completely forgotten about.', 'pos'),
('What''s the most unpleasant texture you''ve ever touched, and what was the context?', 'pos'),
('If your shoes could talk, what embarrassing thing would they reveal about your daily routine?', 'pos'),
('What''s the weirdest object you''ve found under your bed or couch? How long did it take for you to notice it?', 'pos'),
('What would you do if you found a hair in your food at a restaurant, but it wasn''t yours? Describe the situation.', 'pos'),
('What''s the oddest piece of clothing you''ve ever purchased, and how did you feel when you wore it for the first time?', 'pos'),
('Write about a time you accidentally walked into a room where someone was doing something unexpected. How did it feel?', 'pos'),
('What''s the most awkward thing that''s ever happened to you during a job interview?', 'pos'),
('What''s the strangest noise you''ve heard while trying to fall asleep, and how did it affect you?', 'pos'),
('Write about an encounter with an insect that made you feel deeply uncomfortable. What was your immediate reaction?', 'pos'),
('Have you ever accidentally made a face that someone caught on camera? What did the picture look like?', 'pos'),
('What''s the most peculiar thing you''ve seen someone else do in public that made you cringe?', 'pos'),
('What would you do if you found a small, unexpected gift in your mailbox, but it had no sender?', 'pos'),
('Write about a time you were uncomfortably aware of your own breathing. What caused it to become so noticeable?', 'pos'),
('What''s the weirdest food combination you''ve ever tried, and did it end up tasting better or worse than you imagined?', 'pos'),
('Describe the last time you realized your reflection in a public space and had a moment of “what am I doing?”.', 'pos'),
('What''s the most unsettling thing you''ve seen someone else do in the middle of a conversation?', 'pos'),
('Write about a time you were walking behind someone who was doing something totally random, and you didn''t know how to react.', 'pos'),
('Have you ever had a moment where you felt like someone was watching you when they weren''t? How did you react?', 'pos'),
('What''s the most unflattering angle of yourself that you''ve seen in a photograph or video?', 'pos'),
('What''s the strangest thing you''ve witnessed someone do while standing in line at a store?', 'pos'),
('Write about a time you felt trapped in an uncomfortable situation, but there was no escape in sight.', 'pos'),
('What''s the weirdest compliment you''ve ever received, and how did you respond?', 'pos'),
('Describe a time when your body betrayed you in the most awkward way. How did you handle it?', 'pos'),
('What''s the most awkward thing that''s happened to you in a public restroom?', 'pos'),
('Have you ever been caught staring at someone for way too long? What happened next?', 'pos'),
('Write about a time when you realized something was wrong with your appearance after an entire day of being out and about.', 'pos'),
('What''s the strangest place you''ve ever found a piece of food that shouldn''t have been there?', 'pos'),
('Have you ever been caught humming a song out loud that you didn''t realize others could hear? How did it go down?', 'pos'),
('What''s the most uncomfortable thing you''ve heard someone say to you while you were eating?', 'pos'),
('Write about a time when you had to pretend you didn''t see something truly awkward happening in front of you.', 'pos'),
('What''s the oddest excuse you''ve used to avoid an awkward social situation?', 'pos'),
('What would you do if you discovered that someone had been following you for a while but you hadn''t noticed?', 'pos'),
('What''s the strangest way you''ve seen someone try to get out of an embarrassing situation?', 'pos'),
('Write about a time when you accidentally insulted someone but didn''t realize it until much later.', 'pos'),
('What''s the most bizarre thing you''ve ever seen someone do to try to avoid social interaction?', 'pos'),
('Have you ever had a moment where you said something awkward and immediately regretted it? How did you fix it?', 'pos'),
('What''s the most uncomfortable moment you''ve experienced with a public speaker or performer?', 'pos'),
('Write about a time you made a weird noise accidentally in front of a group of people. How did they react?', 'pos'),
('What''s the oddest item you''ve ever purchased because it was on sale but ended up never using?', 'pos'),
('Have you ever forgotten someone''s name during a conversation, but couldn''t remember how to ask without it being awkward?', 'pos'),
('What''s the weirdest thing you''ve done when you thought no one was watching but later discovered they were?', 'pos'),
('Write about a time you tried to avoid eye contact but ended up making it worse. How did you recover?', 'pos'),
('What''s the most awkward handshake you''ve ever had, and how did you handle the aftermath?', 'pos'),
('Write about a time when you noticed someone staring at you for a long period of time. How did you react?', 'pos'),
('What''s the strangest thing that''s ever happened to you while eating in public?', 'pos'),
('Have you ever felt totally out of place at a party or social gathering? What made it so uncomfortable?', 'pos'),
('What''s the weirdest thing that''s happened to you while sitting in a waiting room?', 'pos'),
('Write about a time you saw someone in an extremely unusual outfit in a totally unexpected location.', 'pos'),
('What''s the most uncomfortable moment you''ve ever had while making small talk with a stranger?', 'pos'),
('Describe a time when you tried to be polite, but ended up causing more awkwardness than intended.', 'pos');


-- self-discovery
INSERT INTO journal_prompts (prompt, rating) VALUES
('How do you define your gender identity, and how has your understanding of it evolved over time?', 'pos'),
('What does your sexual orientation mean to you, and how have you come to understand and accept it?', 'pos'),
('Write about a time when you felt truly comfortable in your own skin. What made that moment special?', 'pos'),
('How do you navigate societal expectations related to gender, and how do you feel about them?', 'pos'),
('What aspects of your identity are you still discovering, and how do you feel about the process?', 'pos'),
('Describe your ideal lifestyle. How do you currently live in alignment with that vision?', 'pos'),
('How does your cultural or family background shape your views on gender, sexuality, and relationships?', 'pos'),
('What role does self-expression play in your life, and how do you feel when you''re able to express yourself freely?', 'pos'),
('How has your mindset around politics or social issues changed over the years?', 'pos'),
('What political or social causes are most important to you, and how do you take action to support them?', 'pos'),
('How do you feel about the concept of gender fluidity, and how does it resonate with your personal experiences?', 'pos'),
('What does it mean to you to be “authentic,” and how do you embody authenticity in your everyday life?', 'pos'),
('How have your views on love and relationships evolved over time?', 'pos'),
('What is your personal definition of “success,” and how does it align with your values and goals?', 'pos'),
('How do you feel about the way mainstream society defines masculinity and femininity? Do you agree or disagree?', 'pos'),
('What experiences have shaped your understanding of your sexuality, and how have those experiences influenced who you are today?', 'pos'),
('How do you balance your own identity with societal expectations or pressures?', 'pos'),
('Write about a time when you felt misunderstood because of your gender, sexuality, or beliefs. How did you respond?', 'pos'),
('How do you feel about labels when it comes to gender, sexuality, or lifestyle choices?', 'pos'),
('What role does intersectionality play in your identity, and how do you navigate different aspects of your experience?', 'pos'),
('What does body positivity mean to you, and how do you incorporate it into your life?', 'pos'),
('How do you cope with situations where your identity conflicts with societal norms?', 'pos'),
('Write about a time when you felt empowered by standing up for your beliefs or values. What did it teach you?', 'pos'),
('How do you approach difficult conversations about politics, gender, or sexuality with others?', 'pos'),
('What beliefs about yourself have changed as you''ve grown older? How have these changes shaped who you are today?', 'pos'),
('How do you navigate your identity in the context of family, friends, or community?', 'pos'),
('What aspects of your identity do you feel most proud of, and why?', 'pos'),
('How do you balance individual freedom with the need for social responsibility?', 'pos'),
('What does "living authentically" mean to you, and how do you strive to align your actions with that definition?', 'pos'),
('How do you feel about societal views on polyamory, monogamy, or alternative relationship structures?', 'pos'),
('What challenges have you faced in understanding your own sexual identity, and how have you overcome them?', 'pos'),
('What values do you want to pass on to others, and how do you actively practice those values in your life?', 'pos'),
('Write about a time when you changed your mind about a political or social issue. What prompted the shift?', 'pos'),
('How does your mindset shape the way you approach challenges and setbacks in life?', 'pos'),
('What role does self-reflection play in your journey of self-discovery, and how often do you practice it?', 'pos'),
('How do you navigate the tension between personal freedom and collective responsibility?', 'pos'),
('What are the key factors that influence how you make decisions about your lifestyle, relationships, or career?', 'pos'),
('How do you feel about the concept of "gender roles," and do you think they should change in society?', 'pos'),
('How has your experience with love or intimacy helped shape your understanding of yourself and your needs?', 'pos'),
('What does mental and emotional well-being look like for you, and how do you prioritize it in your life?', 'pos'),
('How do you deal with societal pressure to conform to specific gender or sexual expectations?', 'pos'),
('What is your relationship with religion or spirituality, and how does it shape your worldview?', 'pos'),
('How do you think your gender or sexuality affects how others perceive and treat you in society?', 'pos'),
('What have you learned about yourself through the process of questioning societal norms?', 'pos'),
('How do you express your creativity, and how does that expression reflect who you are as a person?', 'pos'),
('Write about a time when you embraced a new perspective on an issue that once seemed black and white.', 'pos'),
('How do you create a sense of belonging for yourself in a world that often feels divided?', 'pos'),
('What role does vulnerability play in your relationships, and how do you express it?', 'pos'),
('How do you balance your desire for personal growth with the pressures of external expectations?', 'pos'),
('What does “freedom” mean to you in terms of gender, sexuality, and self-expression?', 'pos'),
('How do you feel about labels in terms of your political beliefs or social causes? Do they help or hinder your identity?', 'pos'),
('What changes would you like to see in society to make it more inclusive for people of all genders, sexualities, and lifestyles?', 'pos');

--anxiety
INSERT INTO journal_prompts (prompt, rating) VALUES
('What is your biggest source of personal anxiety right now, and what specific thoughts or situations trigger it?', 'pos'),
('Write about a time when anxiety overtook you in a social situation. What happened, and how did you cope?', 'pos'),
('How do you manage anxiety when thinking about the future? What strategies help you feel more grounded?', 'pos'),
('How do you feel about the state of the world today? What global issues cause you the most anxiety?', 'pos'),
('What are your biggest fears about the future, and how do they impact your mental health?', 'pos'),
('Write about a time when you felt anxiety in a relationship with a friend or family member. How did it affect you?', 'pos'),
('What role does uncertainty play in your anxiety? How do you handle the unknown in your life?', 'pos'),
('How do you feel when you experience anxiety around making decisions? How can you reduce the pressure you feel in those moments?', 'pos'),
('When anxiety strikes, how do you talk to yourself? Are there specific words or phrases that help you calm down?', 'pos'),
('What are the most common physical sensations you experience when you’re feeling anxious, and how do you respond to them?', 'pos'),
('How do you cope with feelings of anxiety when you’re in public spaces or large crowds?', 'pos'),
('Write about a time when you felt overwhelmed by anxiety due to world events. How did you find ways to cope or seek support?', 'pos'),
('What are your biggest fears about your relationships with friends and family, and how do they manifest in anxiety?', 'pos'),
('How does your anxiety change depending on your environment (home, work, social settings)? How can you manage it in each setting?', 'pos'),
('What strategies do you use to quiet the “what-if” thoughts that fuel your anxiety about the future?', 'pos'),
('How do you manage anxiety when you think about the global state of the environment? What can you do to ease your concerns?', 'pos'),
('Write about a time when you were able to confront your anxiety head-on. What did you learn from that experience?', 'pos'),
('How does social media impact your anxiety? What steps can you take to reduce its influence on your well-being?', 'pos'),
('What are some ways you can set boundaries with family and friends when their actions or words trigger your anxiety?', 'pos'),
('What role does self-compassion play in easing your anxiety, and how can you practice it more often?', 'pos'),
('How do you feel about your ability to handle future challenges? How does that contribute to your anxiety?', 'pos'),
('What impact does a lack of control have on your anxiety, and how do you try to regain a sense of control when it feels lost?', 'pos'),
('How does your anxiety affect your decision-making process? Write about a time when anxiety influenced a choice you made.', 'pos'),
('What are the most helpful coping mechanisms you’ve learned for managing anxiety in social situations?', 'pos'),
('How do you feel when you’re overwhelmed by anxiety about not meeting your own or others’ expectations?', 'pos'),
('Write about a time when you experienced anxiety in a family gathering. What triggered it, and how did you deal with it?', 'pos'),
('What does your anxiety about the future look like? How can you stay present and focused in the moment?', 'pos'),
('What support do you need from friends and family when anxiety becomes overwhelming, and how can you ask for it?', 'pos'),
('How does the news or media influence your anxiety, and what steps can you take to manage your exposure to it?', 'pos'),
('What thoughts or beliefs about yourself amplify your anxiety, and how can you challenge or reframe them?', 'pos'),
('How do you deal with the fear of judgment or rejection from others? How does this affect your anxiety in social settings?', 'pos'),
('Write about a time when you were able to use relaxation or grounding techniques to manage anxiety. What worked best for you?', 'pos'),
('How do you differentiate between anxiety and excitement? What strategies help you identify and manage both emotions?', 'pos'),
('What are some activities or hobbies that help you cope with anxiety and bring you a sense of peace?', 'pos'),
('How does being away from home or in an unfamiliar place trigger your anxiety? How do you find comfort in these situations?', 'pos'),
('Write about a time when anxiety caused a strain in your friendships. How did you address it or seek resolution?', 'pos'),
('How do you handle the uncertainty of not knowing what tomorrow will bring? What techniques help you feel more at ease with the unknown?', 'pos'),
('What role does perfectionism play in your anxiety, and how can you challenge this mindset?', 'pos'),
('How do you respond when you feel anxiety about not being able to control the actions or outcomes of others?', 'pos'),
('Write about a time when you were able to manage anxiety during a stressful work situation. What helped you stay calm?', 'pos'),
('How does the idea of “fitting in” with others create anxiety for you, and what can you do to embrace your uniqueness?', 'pos'),
('What are the most challenging aspects of living with anxiety, and how have you learned to navigate them?', 'pos'),
('How does your anxiety influence the way you perceive the world around you? How can you shift this perspective?', 'pos'),
('What role does gratitude play in alleviating your anxiety, and how can you cultivate more of it in your life?', 'pos'),
('How do you manage the feeling of being overwhelmed by your responsibilities or commitments? What helps you regain focus?', 'pos'),
('Write about a time when you felt social anxiety in a group setting. How did you manage the experience?', 'pos'),
('What does it mean to you to “take care of yourself” when dealing with anxiety, and what steps can you take to prioritize self-care?', 'pos'),
('What does “letting go” of control mean to you, and how can it reduce anxiety in your life?', 'pos'),
('How does your physical health (sleep, diet, exercise) impact your anxiety levels, and what changes can you make to improve it?', 'pos'),
('Write about a time when you felt anxiety related to your career or future goals. How did you navigate this anxiety?', 'pos'),
('What does it feel like when you experience a panic attack? How do you ground yourself in those moments?', 'pos'),
('How do you support friends or family members who struggle with anxiety, and how does this influence your own anxiety?', 'pos');


INSERT INTO journal_prompts (prompt, rating) VALUES
('What would your life look like if you let go of the fear of failure? How would your actions change?', 'pos'),
('Write about a time you made a decision that seemed small at the time but turned out to be life-changing.', 'pos'),
('If your future self could give you one piece of advice, what would it be?', 'pos'),
('Write about a passion of yours that you''ve never pursued. What''s holding you back from exploring it?', 'pos'),
('What''s the most challenging belief you hold about yourself? How does this belief shape your life?', 'pos'),
('Describe your ideal version of success. How does it differ from the typical societal definition of success?', 'pos'),
('If you were to write a letter to your younger self, what would you say?', 'pos'),
('Write about a fear you''ve overcome. How did it feel to face it, and what did you learn from the experience?', 'pos'),
('What''s a habit you''ve always wanted to form, but have struggled to stick with? What do you think is the underlying reason?', 'pos'),
('If you could ask a mentor or role model any question, what would it be and why?', 'pos'),
('When was the last time you felt completely aligned with your values? What were you doing at the time?', 'pos'),
('What does self-care look like for you, and how can you incorporate it more fully into your life?', 'pos'),
('How do you respond to criticism? How can you reshape your response to be more constructive and less personal?', 'pos'),
('Write about an activity or hobby that allows you to get lost in the moment. What makes it so engaging for you?', 'pos'),
('How do you know when it''s time to let go of something—whether a belief, a habit, or a relationship?', 'pos'),
('What is something that inspires you to be better? How can you actively incorporate this inspiration into your life?', 'pos'),
('What''s one thing you wish more people understood about you? Why do you think it''s difficult for others to grasp?', 'pos'),
('If you had no limitations, what would you spend your time doing? Why are you drawn to these activities?', 'pos'),
('How do you navigate moments of doubt? What helps you find clarity when you''re unsure?', 'pos'),
('If you could switch lives with someone for a day, who would it be and why?', 'pos'),
('Write about a time when you felt out of your comfort zone but grew as a result. What did you learn from that experience?', 'pos'),
('What does it mean to be brave? Write about a moment where you exhibited courage, even if it didn''t feel that way at the time.', 'pos'),
('If you could live in any fictional world, which one would you choose and why?', 'pos'),
('What does balance look like for you? How can you achieve more balance in your personal and professional life?', 'pos'),
('If you had the power to change one thing about society, what would it be? Why is this issue important to you?', 'pos'),
('What does vulnerability mean to you? How does it show up in your relationships and interactions with others?', 'pos'),
('Write about a time when you felt truly understood. What made that connection so meaningful to you?', 'pos'),
('If you could rid yourself of one fear, what would it be and how would your life change?', 'pos'),
('What does your inner voice sound like? How can you cultivate a more compassionate and constructive inner dialogue?', 'pos'),
('How do you deal with the unknown in life? What tools or practices help you face uncertainty without overwhelming anxiety?', 'pos'),
('What are your non-negotiables in life? What values or boundaries do you refuse to compromise on?', 'pos'),
('Write about a time you learned an important lesson through failure. How did it change your perspective?', 'pos'),
('If you could give one piece of advice to someone going through a tough time, what would you tell them?', 'pos'),
('What is something that feels like a hidden talent or gift you have, but haven''t fully explored yet?', 'pos'),
('If you could have a conversation with your future self, what would you ask? What would you hope they say?', 'pos'),
('What''s the most meaningful compliment you''ve ever received? How did it make you feel?', 'pos'),
('Write about a moment in your life that made you feel truly proud of yourself. What was the context, and why did it matter so much?', 'pos'),
('How do you nurture your creativity? What activities or practices help you tap into your most creative self?', 'pos'),
('What''s a personal mantra or quote that resonates with you? Why do those words stick with you?', 'pos'),
('If you could create your own holiday, what would it celebrate and how would people observe it?', 'pos'),
('Write about a time you took a risk that paid off. How did you weigh the decision, and what were the outcomes?', 'pos'),
('What does it mean to you to be “at peace”? How can you cultivate more of that peace in your daily life?', 'pos'),
('Write about a place that feels like home to you, even if it''s not where you live. What about it makes you feel comfortable and safe?', 'pos'),
('How do you deal with disappointment? What have you learned from moments where expectations weren''t met?', 'pos'),
('If you could contribute to any cause or movement, what would it be and why does it matter to you?', 'pos'),
('What does it mean to you to be authentic in today''s world? How can you stay true to yourself while navigating societal pressures?', 'pos'),
('Write about a time you felt deeply connected to nature. What about that experience made it so profound?', 'pos'),
('What would you do if you knew you could not fail? How would you approach your goals and dreams?', 'pos'),
('What''s the most difficult conversation you''ve had with someone, and how did it affect your relationship?', 'pos');
